tap "homebrew/bundle"
cask "font-jetbrains-mono-nerd-font"
cask "iterm2"
cask "jordanbaird-ice"
cask "raycast"
cask "setapp"
cask "syncthing"
cask "telegram"
cask "vivaldi"
mas "Reeder", id: 1529448980
mas "WireGuard", id: 1451685025
