{ pkgs, ... }: {
  programs.home-manager.enable = true;

  home.packages = with pkgs; [
    stow
    tdesktop
  ];

  programs.firefox.enable = true;
  programs.fzf.enable = true;
  programs.git = {
    enable = true;
    userName = "Heng-Yi Wu";
    userEmail = "2316687+henry40408@users.noreply.github.com";
    extraConfig = {
      commit.gpgsign = true;
      user.signingKey = "2316687+henry40408@users.noreply.github.com";
    };
  };
  programs.neovim = {
    enable = true;
    plugins = with pkgs.vimPlugins; [
      # vim plugins
      base16-vim
      rainbow
      vim-better-whitespace
      vim-easymotion
      vim-fugitive
      vim-surround
      vim-unimpaired
      zoomwintab-vim

      # neovim plugins
      comment-nvim
      editorconfig-nvim
      gitsigns-nvim
      indent-blankline-nvim
      lualine-nvim
      nvim-treesitter
      nvim-treesitter-context
      nvim-web-devicons
      plenary-nvim
      registers-nvim
      toggleterm-nvim
      vim-fetch
      vim-which-key
    ];
    extraConfig = ''
    " Generated by home-manager
    lua << EOF
    vim.cmd([[colorscheme base16-irblack]])
    EOF
    '';
  };

  services.gpg-agent = {
    enable = true;
    enableSshSupport = true;
    sshKeys = [ "B9D979480FA655AF6FDE0459F4F330B5D80452EF" ];
  };
  services.syncthing.enable = true;
}
