{ pkgs, ... }: let
  dotfiles = builtins.fetchTarball {
    url = "https://github.com/henry40408/dotfiles/archive/d923ce4a2a33b21c2069886f17da20b10ca72262.tar.gz";
    sha256 = "102hf35j9k5q9flazs2xwda8irvddlkkgj0xq7a8643rnbfwba28";
  };
in {
  programs.home-manager.enable = true;

  home.file.".config/nvim/lua".recursive = true;
  home.file.".config/nvim/lua".source = dotfiles + "/vim/.config/nvim/lua";

  # init.lua and init.vim is mutually exclusive
  home.file.".config/nvim/lua/noConflict.lua".source = dotfiles + "/vim/.config/nvim/init.lua";

  home.file.".gemrc".source = dotfiles + "/ruby/.gemrc";
  home.file.".p10k.zsh".source = dotfiles + "/zsh/.p10k.zsh";
  home.file.".tmux.conf".source = dotfiles + "/tmux/.tmux.conf";
  home.file.".zshrc".source = dotfiles + "/zsh/.zshrc";

  home.packages = with pkgs; [
    # previously managed by asdf
    consul
    deno
    doctl
    fd
    go
    google-cloud-sdk
    kubernetes-helm
    k9s
    kubectl
    mkcert
    nodejs
    python37
    ripgrep
    ruby_3_1
    rustup
    terraform
    tflint
    tmux
    yarn

    # rust crates
    cargo-cross
    du-dust
    delta
    hyperfine
    license-generator
    lsd
    procs
    stylua
    tokei
    xsv
    zoxide

    # CLI
    direnv
    xclip

    # GUI
    tdesktop
    jetbrains.idea-ultimate
  ];

  programs.firefox.enable = true;
  programs.fzf.enable = true;
  programs.git = {
    enable = true;
    userName = "Heng-Yi Wu";
    userEmail = "2316687+henry40408@users.noreply.github.com";
    extraConfig = {
      commit.gpgsign = true;
      core.pager = "delta";
      delta = {
        navigate = true;
        side-by-side = true;
      };
      diff.colorMoved = "default";
      merge.conflictstyle = "diff3";
      user.signingKey = "2316687+henry40408@users.noreply.github.com";
    };
  };

  programs.bat.enable = true;
  programs.gh.enable = true;
  programs.neovim = {
    enable = true;
    plugins = with pkgs.vimPlugins; [
      packer-nvim
    ];
    extraConfig = ''
    " Generated by home-manager
    lua << EOF
    require('noConflict')
    EOF
    '';
  };

  services.gpg-agent = {
    enable = true;
    enableSshSupport = true;
    sshKeys = [ "B9D979480FA655AF6FDE0459F4F330B5D80452EF" ];
  };
  services.syncthing.enable = true;
}

# vim: set sw=2:
