tap "beeftornado/rmtree"
tap "homebrew/bundle"
tap "homebrew/cask-fonts"
tap "xcodesorg/made"
brew "aria2"
brew "automake"
brew "gnupg"
brew "mackup"
brew "mas"
brew "pkg-config"
brew "xcodesorg/made/xcodes"
cask "font-jetbrains-mono-nerd-font"
cask "iterm2"
cask "raycast"
cask "setapp"
cask "syncthing"
cask "vivaldi"
mas "Amphetamine", id: 937984704
mas "Hidden Bar", id: 1452453066
mas "Reeder", id: 1529448980
mas "WireGuard", id: 1451685025
